"use client";

import Head from "next/head";
import Image from "next/image";
import ProfileImage from "../assets/pic5.png";
import Waves2 from "../assets/gravity_waves2.svg";
import React from "react";
import CV from "../components/cv";
import Hero from "../components/hero";

export default function Home() {
  return (
    <article className=" relative flex flex-col items-center">
      <Head>
        <title>My Homepage - Marco Fähndrich</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero></Hero>

      <div className="relative flex w-full flex-col items-center justify-stretch bg-gray-900">
        <div className="absolute bottom-0 h-64 w-full">
          <Image src={Waves2} layout="fill" alt="waves" />
        </div>

        <section className="w-full max-w-6xl">
          <div className="relative flex h-96 w-full flex-col items-end justify-end overflow-hidden rounded-3xl md:flex-row ">
            <div className="absolute flex w-full items-center rounded-3xl bg-gradient-to-r from-indigo-300 to-cyan-200 p-6 pr-72 md:h-72">
              <div className="flex flex-col items-start gap-3">
                <h2 className="font-montserat text-4xl font-bold text-slate-800">
                  Ich bin einfach der Coolste
                </h2>
                <p className="max-w-3xl font-nunito text-2xl text-slate-800">
                  Or neglected agreeable of discovery concluded oh it sportsman. Week to time in
                  john. Son elegance use weddings separate.
                </p>
                <button className="flex  flex-row items-center justify-between gap-6 rounded-full bg-slate-800 px-8 py-3 font-montserat text-lg font-semibold text-white hover:shadow-lg hover:shadow-black/50">
                  Call me maybe
                </button>
              </div>
            </div>
            <div className="relative flex">
              {/* <div className="absolute bottom-0 h-72 w-72 rounded-t-full bg-[#161F33]"></div> */}
              <Image
                layout="fixed"
                height={380}
                width={320}
                src={ProfileImage}
                alt="Profile Picture"
                // style={{ maskImage: `url(${Mask.src})` }}
              />
            </div>
          </div>
          <div className="spacer h-72"></div>
        </section>
      </div>

      <CV></CV>
    </article>
  );
}
