import Head from "next/head";
import Image from "next/image";
import Waves from "../assets/gravity_waves.svg";
import Moon from "../assets/moon_half.png";
import ProfileImage from "../assets/pic5.png";
import Stars from "../assets/stars.svg";

export default function Home() {
  return (
    <div className=" relative flex flex-col items-center">
      <Head>
        <title>My Homepage - Marco Fähndrich</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div
        className="absolute inset-0 h-screen w-screen"
        style={{ backgroundImage: `url(${Stars.src})` }}></div>

      <div className="relative flex w-full justify-center overflow-hidden">
        <div className="absolute top-0 h-[60%] w-full opacity-50">
          <Image src={Moon} layout="fill" objectFit="contain" alt="Moon" />
        </div>
        <div className="absolute bottom-0 h-[40%] w-full">
          <Image src={Waves} layout="fill" alt="waves" />
        </div>

        <div className="bg-url mx-6 w-full max-w-6xl">
          <section id="hero" className=" flex h-screen items-center">
            <div className="z-10 flex flex-col items-center md:flex-row">
              <div className="p-3 md:flex-1">
                <h1 className="mb-3 font-ps2p text-3xl text-white md:text-5xl">Marco Fähndrich</h1>
                <h3 className="text-lg text-white md:text-xl">
                  Ich muss dir was ganz wichtiges sagen. Ich könnts dir jetzt sagen, aber ich sags
                  dir lieber morgen.
                </h3>
                <div className="mt-6 flex gap-3">
                  <button className="flex  flex-row items-center justify-between gap-6 rounded-full bg-gradient-to-r from-purple-500 to-yellow-500 px-8 py-3 font-montserat text-lg font-semibold text-white hover:shadow-lg hover:shadow-white/50">
                    Klick
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      fill="none"
                      viewBox="0 0 24 24"
                      strokeWidth="3.5"
                      stroke="currentColor"
                      className="h-6 w-6">
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        d="M8.25 4.5l7.5 7.5-7.5 7.5"
                      />
                    </svg>
                  </button>
                  <button className="flex flex-row items-center gap-6 rounded-full bg-white px-8 py-3 font-montserat text-lg font-semibold text-gray-700 hover:shadow-lg hover:shadow-white/50">
                    Klack
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      fill="none"
                      viewBox="0 0 24 24"
                      strokeWidth="3.5"
                      stroke="currentColor"
                      className="h-6 w-6">
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        d="M8.25 4.5l7.5 7.5-7.5 7.5"
                      />
                    </svg>
                  </button>
                </div>
              </div>
              <div className="flex flex-1 justify-center">
                <div className="rounded-[0_0_999px_300px] justify-center relative flex h-96 w-72 items-end overflow-hidden">
                  <div className="absolute h-72 w-72  rounded-[999px_300px] bg-yellow-500"></div>
                  <Image
                    layout="fixed"
                    height={380}
                    width={320}
                    src={ProfileImage}
                    alt="Profile Picture"
                    // style={{ maskImage: `url(${Mask.src})` }}
                  />
                </div>
              </div>
            </div>
          </section>
        </div>
      </div>

      <div className=" w-full bg-gray-800">
        <section className="flex max-w-6xl justify-center">
          <h2 className="font-white text-4xl text-white">Ciruculum Vitae</h2>
          <div className="flex h-[2000px] flex-row justify-evenly py-24">
            <div className="flex h-full flex-none flex-col justify-evenly">
              {[...Array(28).keys()].map((x) => (
                <div key={x} className="flex flex-row items-center ">
                  <div className="font-bold text-white">{x + 1995}</div>
                  <div className="ml-3 h-3 w-3 rounded-full bg-white text-white"></div>
                  <div className="h-[1px] w-12 bg-white text-white"></div>
                </div>
              ))}
            </div>
            <div className="relative flex flex-1 flex-row justify-evenly">
              <div>
                <div className="mx-auto h-full w-6 rounded-full bg-gradient-to-b from-purple-600 to-purple-300 drop-shadow-md-white"></div>
                <div className="absolute top-0 h-12  w-12 rounded-full bg-white drop-shadow-md-white"></div>
                <div className="sticky bottom-0 rounded-t-full bg-gray-800">
                  <div className=" h-12 w-12 rounded-full bg-white drop-shadow-md-white"></div>
                </div>
              </div>
              <div>
                <div className="mx-auto h-full w-6 rounded-full bg-gradient-to-b from-emerald-600 to-emerald-300 drop-shadow-md-white"></div>
                <div className="absolute top-0 h-12 w-12 rounded-full bg-white drop-shadow-md-white"></div>
                <div className="sticky bottom-0 rounded-t-full bg-gray-800">
                  <div className=" h-12 w-12 rounded-full bg-white drop-shadow-md-white"></div>
                </div>
              </div>
              <div>
                <div className="mx-auto h-full w-6 rounded-full bg-gradient-to-b from-orange-600 to-orange-300 drop-shadow-md-white"></div>
                <div className="absolute top-0 h-12 w-12 rounded-full bg-white drop-shadow-md-white"></div>
                <div className="sticky bottom-0 rounded-t-full bg-gray-800">
                  <div className=" h-12 w-12 rounded-full bg-white drop-shadow-md-white"></div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>
    </div>
  );
}
